# Generated by Django 3.1.5 on 2021-01-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doner_details',
            fields=[
                ('donor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=20)),
                ('contect_no', models.IntegerField(max_length=10)),
                ('blood_group', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
    ]
