# Generated by Django 3.1.5 on 2021-03-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=20)),
                ('contect_no', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Donor_details',
        ),
    ]
