# Generated by Django 3.1.5 on 2021-02-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner_details',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
    ]
