# Generated by Django 3.1.5 on 2021-03-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorreg', '0002_auto_20210306_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
