# Generated by Django 3.1.5 on 2021-02-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstdbtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_dob',
        ),
    ]
